before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: d75TzAiqwoMw8SvHSoABDZFore82jpFEbAAILiKnYliIc+nZA/tlZ9O24zebJ1x/2UgtfhJfsvbqSMCoQhO5rq2b9h5KE1gT4RvbIXYPTMFTq89ROx/+tF5PTI+LtqeKanMJZgTERQ8EphA8h9XptCG5jW+vV2uJmhgOiy076G8oL6h+G6DgrXfX8oPml4ha6xBa4IJXO9AivHdoT8HWsjtWIGNlfDOFuYVsZfyJn43E2fURe+xYYV3oS85+Rw06URSha6Xr61JgetHqTsdYYviSxl0g9NjQDv/f94MYgF/op3NMcM3KZTtWYH8vl1YadC9n4ibobcpjFYXeVF3ZlnoGv2HVdt3qyN/sk/DPcU97Uu5Aj/TeNahFAfMcnMgnPDAXxClCDfYolPmqt9wZ6/LdxYe87aiQ41B1n40WtyCpI+WqUTL3MY1BVZF34iUyMo6ef2DYFvxYN8wAWdAqnB/sz/3MF9YxFtJStArH9mnbbVomrj+WFlka605JZNeOp1R/QOVDpjKuntsaIsseuGmo7g7SgXIrLhxyOLABBgAlhGWhEo2EAGQWLW0gAIYXsjRPnG+14I4N8A3C5/J3TneWs80eTiGp/2i65T/qzLkbVqJKNLCKSQEQIhcKSHdfCxJ8HCrHfFs1PTwa7TOrVx6VbH6yrdBuUw07PyAk+hw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
